version: "3"

services:
  db:
    image: mysql
    container_name: expense-tracker-db
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    volumes:
      - ./expenseData:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: expense-tracker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony

  frontend:
    image: snaksa/expense-tracker-frontend
    container_name: expense-tracker-frontend
    build:
      context: .
    volumes:
      - ./:/app
    ports:
      - "3000:3000"

  backend:
    image: snaksa/expense-tracker-backend
    container_name: expense-tracker-backend
    environment:
      - DATABASE_URL=mysql://symfony:symfony@db:3306/expense-tracker?serverVersion=5.7
      - JWT_PASSPHRASE=expensestracker2020
    links:
      - db
    ports:
      - "8080:80"
